name: PlantUML Diagrams

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.puml'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate-plantuml-svg:
    name: Plant UML
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: docs/images
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
