name: Source Code Build and Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**/Makefile'
      - src/**/*.cc
      - src/**/*.h
      - test/**/*.cc
      - test/**/*.h
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-unittest:
    name: Compile and run unit tests
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: |
        cd src
        make

    - name: Setup Tools
      run: |
        sudo apt install -y cpputest lcov

    - name: Run tests
      run: |
        cd test
        make test
        make coverage

    - name: Update coverage report
      run: |
        git config --global user.email "benitogothethird@hotmail.com"
        git config --global user.name "Benito Go III"
        git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/nitoygo/toy-robot
        git add reports
        git commit -m "Update reports"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/nitoygo/toy-robot

  static-code-check:
    name: Check for static code errors and warnings
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        std: c++20
        exclude_check: test
        output_file: ./reports/static/cppcheck_report.txt

    - name: Update cppcheck report
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main'
