name: Toy Robot Source Update CI

on:
  push:
    branches: [ main ]
    paths:
      - src/**
      - test/**
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-unittest:
    name: Compile and run unit tests
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: |
        cd src
        make

    - name: Run tests
      run: |
        sudo apt-get update
        sudo apt install -y cpputest
        cd test
        make

  static-code-check:
    name: Check for static code errors and warnings
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        std: c++20
        output_file: ./reports/static/cppcheck_report.txt

    - name: Publish cppcheck report    
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main'
